from typing import Any, Final

ERROR_COLUMN_NAME: Final = "Error"
TAB_GENERAL: Final = "General"
TAB_PRICE_ITEMS: Final = "Price Items"
REQUIRED_TABS: Final = (
    TAB_GENERAL,
    TAB_PRICE_ITEMS,
)

REQUIRED_FIELDS_BY_TAB: Final[dict[str, Any]] = {}

GENERAL_PRICELIST_ID: Final = "Pricelist ID"
GENERAL_CURRENCY: Final = "Currency"
GENERAL_PRODUCT_ID: Final = "Product ID"
GENERAL_PRODUCT_NAME: Final = "Product Name"
GENERAL_VENDOR_ID: Final = "Vendor ID"
GENERAL_VENDOR_NAME: Final = "Vendor Name"
GENERAL_EXPORT_DATE: Final = "Export Date"
GENERAL_PRECISION: Final = "Precision"
GENERAL_DEFAULT_MARKUP: Final = "Default Markup"
GENERAL_NOTES: Final = "Notes"
GENERAL_CREATED: Final = "Created"
GENERAL_MODIFIED: Final = "Modified"
EXTERNAL_ID: Final = "External ID"

GENERAL_FIELDS: Final = (
    GENERAL_PRICELIST_ID,
    GENERAL_CURRENCY,
    GENERAL_PRODUCT_ID,
    GENERAL_PRODUCT_NAME,
    GENERAL_VENDOR_ID,
    GENERAL_VENDOR_NAME,
    GENERAL_EXPORT_DATE,
    GENERAL_PRECISION,
    GENERAL_DEFAULT_MARKUP,
    GENERAL_NOTES,
    GENERAL_CREATED,
    GENERAL_MODIFIED,
    EXTERNAL_ID,
)

PRICELIST_ITEMS_ID: Final = "ID"
PRICELIST_ITEMS_ITEM_ID: Final = "Item ID"
PRICELIST_ITEMS_ITEM_NAME: Final = "Item Name"
PRICELIST_ITEMS_ACTION: Final = "Action"
PRICELIST_ITEMS_ITEM_VENDOR_ID: Final = "Item Vendor ID"
PRICELIST_ITEMS_ITEM_ERP_ID: Final = "Item ERP ID"
PRICELIST_ITEMS_BILLING_FREQUENCY: Final = "Billing Frequency"
PRICELIST_ITEMS_COMMITMENT: Final = "Commitment"
PRICELIST_ITEMS_UNIT_LP: Final = "Unit LP"
PRICELIST_ITEMS_UNIT_PP: Final = "Unit PP"
PRICELIST_ITEMS_MARKUP: Final = "Markup"
PRICELIST_ITEMS_PPx1: Final = "PPx1"
PRICELIST_ITEMS_PPxM: Final = "PPxM"
PRICELIST_ITEMS_PPxY: Final = "PPxY"
PRICELIST_ITEMS_UNIT_SP: Final = "Unit SP"
PRICELIST_ITEMS_SPx1: Final = "SPx1"
PRICELIST_ITEMS_SPxM: Final = "SPxM"
PRICELIST_ITEMS_SPxY: Final = "SPxY"
PRICELIST_ITEMS_LPx1: Final = "LPx1"
PRICELIST_ITEMS_LPxM: Final = "LPxM"
PRICELIST_ITEMS_LPxY: Final = "LPxY"
PRICELIST_ITEMS_STATUS: Final = "Status"
PRICELIST_ITEMS_MODIFIED: Final = "Modified"
PRICELIST_ITEMS_FIELDS: Final = (
    PRICELIST_ITEMS_ID,
    PRICELIST_ITEMS_ITEM_ID,
    PRICELIST_ITEMS_ITEM_NAME,
    PRICELIST_ITEMS_ITEM_VENDOR_ID,
    PRICELIST_ITEMS_ITEM_ERP_ID,
    PRICELIST_ITEMS_BILLING_FREQUENCY,
    PRICELIST_ITEMS_COMMITMENT,
    PRICELIST_ITEMS_UNIT_LP,
    PRICELIST_ITEMS_UNIT_PP,
    PRICELIST_ITEMS_MARKUP,
    PRICELIST_ITEMS_PPx1,
    PRICELIST_ITEMS_PPxM,
    PRICELIST_ITEMS_PPxY,
    PRICELIST_ITEMS_UNIT_SP,
    PRICELIST_ITEMS_SPx1,
    PRICELIST_ITEMS_SPxM,
    PRICELIST_ITEMS_SPxY,
    PRICELIST_ITEMS_LPx1,
    PRICELIST_ITEMS_LPxM,
    PRICELIST_ITEMS_LPxY,
    PRICELIST_ITEMS_STATUS,
    PRICELIST_ITEMS_ACTION,
    PRICELIST_ITEMS_MODIFIED,
)
