from typing import Final

ID_COLUMN_NAME: Final = "ID"
ACTION_COLUMN_NAME: Final = "Action"
CREATED_COLUMN_NAME: Final = "Created"
DISPLAY_ORDER_COLUMN_NAME: Final = "Display Order"
MODIFIED_COLUMN_NAME: Final = "Modified"
ERROR_COLUMN_NAME: Final = "Error"

# Tabs definition
TAB_GENERAL: Final = "General"
TAB_PARAMETERS_GROUPS: Final = "Parameters Groups"
TAB_ITEMS_GROUPS: Final = "Items Groups"
TAB_AGREEMENT_PARAMETERS: Final = "Agreements Parameters"
TAB_ASSET_PARAMETERS: Final = "Assets Parameters"
TAB_ITEM_PARAMETERS: Final = "Item Parameters"
TAB_REQUEST_PARAMETERS: Final = "Request Parameters"
TAB_SUBSCRIPTION_PARAMETERS: Final = "Subscription Parameters"
TAB_ITEMS: Final = "Items"
TAB_TEMPLATES: Final = "Templates"
TAB_SETTINGS: Final = "Settings"
ALL_TABS: Final = (
    TAB_GENERAL,
    TAB_PARAMETERS_GROUPS,
    TAB_ITEMS_GROUPS,
    TAB_AGREEMENT_PARAMETERS,
    TAB_ASSET_PARAMETERS,
    TAB_ITEM_PARAMETERS,
    TAB_REQUEST_PARAMETERS,
    TAB_SUBSCRIPTION_PARAMETERS,
    TAB_ITEMS,
    TAB_TEMPLATES,
    TAB_SETTINGS,
)
REQUIRED_TABS: Final = (
    TAB_GENERAL,
    TAB_SETTINGS,
)


# General tab definition
GENERAL_PRODUCT_ID: Final = "Product ID"
GENERAL_PRODUCT_NAME: Final = "Product Name"
GENERAL_ACCOUNT_ID: Final = "Account ID"
GENERAL_ACCOUNT_NAME: Final = "Account Name"
GENERAL_EXPORT_DATE: Final = "Export Date"
GENERAL_PRODUCT_WEBSITE: Final = "Product Website"
GENERAL_CATALOG_DESCRIPTION: Final = "Catalog Description"
GENERAL_PRODUCT_DESCRIPTION: Final = "Product Description"
GENERAL_STATUS: Final = "Status"
GENERAL_CREATED: Final = CREATED_COLUMN_NAME
GENERAL_MODIFIED: Final = "Modified"
GENERAL_FIELDS: Final = (
    GENERAL_PRODUCT_ID,
    GENERAL_PRODUCT_NAME,
    GENERAL_ACCOUNT_ID,
    GENERAL_ACCOUNT_NAME,
    GENERAL_EXPORT_DATE,
    GENERAL_PRODUCT_WEBSITE,
    GENERAL_CATALOG_DESCRIPTION,
    GENERAL_PRODUCT_DESCRIPTION,
    GENERAL_STATUS,
    GENERAL_CREATED,
    GENERAL_MODIFIED,
)
GENERAL_REQUIRED_FIELDS: Final = (
    GENERAL_PRODUCT_ID,
    GENERAL_PRODUCT_NAME,
    GENERAL_PRODUCT_WEBSITE,
    GENERAL_CATALOG_DESCRIPTION,
    GENERAL_PRODUCT_DESCRIPTION,
)
GENERAL_REQUIRED_FIELDS_WITH_VALUES: Final = (
    GENERAL_PRODUCT_NAME,
    GENERAL_PRODUCT_WEBSITE,
)

# Parameters Groups tab definition
PARAMETERS_GROUPS_ID: Final = ID_COLUMN_NAME
PARAMETERS_GROUPS_NAME: Final = "Name"
PARAMETERS_GROUPS_ACTION: Final = ACTION_COLUMN_NAME
PARAMETERS_GROUPS_LABEL: Final = "Label"
PARAMETERS_GROUPS_DISPLAY_ORDER: Final = DISPLAY_ORDER_COLUMN_NAME
PARAMETERS_GROUPS_DESCRIPTION: Final = "Description"
PARAMETERS_GROUPS_DEFAULT: Final = "Default"
PARAMETERS_GROUPS_CREATED: Final = "Created"
PARAMETERS_GROUPS_MODIFIED: Final = MODIFIED_COLUMN_NAME
PARAMETERS_GROUPS_REQUIRED_FIELDS: Final = (
    PARAMETERS_GROUPS_ID,
    PARAMETERS_GROUPS_NAME,
    PARAMETERS_GROUPS_ACTION,
    PARAMETERS_GROUPS_LABEL,
    PARAMETERS_GROUPS_DISPLAY_ORDER,
    PARAMETERS_GROUPS_DEFAULT,
)
PARAMETERS_GROUPS_FIELDS: Final = (
    PARAMETERS_GROUPS_ID,
    PARAMETERS_GROUPS_NAME,
    PARAMETERS_GROUPS_ACTION,
    PARAMETERS_GROUPS_LABEL,
    PARAMETERS_GROUPS_DISPLAY_ORDER,
    PARAMETERS_GROUPS_DESCRIPTION,
    PARAMETERS_GROUPS_DEFAULT,
    PARAMETERS_GROUPS_CREATED,
    PARAMETERS_GROUPS_MODIFIED,
)

# Items Groups tab definition
ITEMS_GROUPS_ID: Final = ID_COLUMN_NAME
ITEMS_GROUPS_NAME: Final = "Name"
ITEMS_GROUPS_ACTION: Final = ACTION_COLUMN_NAME
ITEMS_GROUPS_LABEL: Final = "Label"
ITEMS_GROUPS_DISPLAY_ORDER: Final = DISPLAY_ORDER_COLUMN_NAME
ITEMS_GROUPS_DESCRIPTION: Final = "Description"
ITEMS_GROUPS_DEFAULT: Final = "Default"
ITEMS_GROUPS_MULTIPLE_CHOICES: Final = "Multiple Choice"
ITEMS_GROUPS_REQUIRED: Final = "Required"
ITEMS_GROUPS_CREATED: Final = CREATED_COLUMN_NAME
ITEMS_GROUPS_MODIFIED: Final = MODIFIED_COLUMN_NAME
ITEMS_GROUPS_REQUIRED_FIELDS: Final = (
    ITEMS_GROUPS_ID,
    ITEMS_GROUPS_NAME,
    ITEMS_GROUPS_ACTION,
    ITEMS_GROUPS_LABEL,
    ITEMS_GROUPS_DISPLAY_ORDER,
    ITEMS_GROUPS_DESCRIPTION,
    ITEMS_GROUPS_DEFAULT,
    ITEMS_GROUPS_MULTIPLE_CHOICES,
    ITEMS_GROUPS_REQUIRED,
)
ITEMS_GROUPS_FIELDS: Final = (
    ITEMS_GROUPS_ID,
    ITEMS_GROUPS_NAME,
    ITEMS_GROUPS_ACTION,
    ITEMS_GROUPS_LABEL,
    ITEMS_GROUPS_DISPLAY_ORDER,
    ITEMS_GROUPS_DESCRIPTION,
    ITEMS_GROUPS_DEFAULT,
    ITEMS_GROUPS_MULTIPLE_CHOICES,
    ITEMS_GROUPS_REQUIRED,
    ITEMS_GROUPS_CREATED,
    ITEMS_GROUPS_MODIFIED,
)

# Agreement, Item, Request, Subscription Parameters tab definition
PARAMETERS_ID: Final = ID_COLUMN_NAME
PARAMETERS_NAME: Final = "Name"
PARAMETERS_EXTERNALID: Final = "ExternalId"
PARAMETERS_DESCRIPTION: Final = "Description"
PARAMETERS_ACTION: Final = ACTION_COLUMN_NAME
PARAMETERS_PHASE: Final = "Phase"
PARAMETERS_TYPE: Final = "Type"
PARAMETERS_GROUP_ID: Final = "Group ID"
PARAMETERS_GROUP_NAME: Final = "Group Name"
PARAMETERS_OPTIONS: Final = "Options"
PARAMETERS_CONSTRAINTS: Final = "Constraints"
PARAMETERS_DISPLAY_ORDER: Final = DISPLAY_ORDER_COLUMN_NAME
PARAMETERS_CREATED: Final = CREATED_COLUMN_NAME
PARAMETERS_MODIFIED: Final = MODIFIED_COLUMN_NAME
PARAMETERS_REQUIRED_FIELDS: Final = (
    PARAMETERS_ID,
    PARAMETERS_NAME,
    PARAMETERS_EXTERNALID,
    PARAMETERS_ACTION,
    PARAMETERS_PHASE,
    PARAMETERS_TYPE,
    PARAMETERS_GROUP_ID,
    PARAMETERS_OPTIONS,
    PARAMETERS_CONSTRAINTS,
    PARAMETERS_DISPLAY_ORDER,
    PARAMETERS_DESCRIPTION,
)
PARAMETERS_FIELDS: Final = (
    PARAMETERS_ID,
    PARAMETERS_NAME,
    PARAMETERS_EXTERNALID,
    PARAMETERS_ACTION,
    PARAMETERS_PHASE,
    PARAMETERS_TYPE,
    PARAMETERS_GROUP_ID,
    PARAMETERS_GROUP_NAME,
    PARAMETERS_OPTIONS,
    PARAMETERS_CONSTRAINTS,
    PARAMETERS_DISPLAY_ORDER,
    PARAMETERS_CREATED,
    PARAMETERS_MODIFIED,
    PARAMETERS_DESCRIPTION,
)

# Items tab definition
ITEMS_ID: Final = ID_COLUMN_NAME
ITEMS_NAME: Final = "Name"
ITEMS_ACTION: Final = ACTION_COLUMN_NAME
ITEMS_VENDOR_ITEM_ID: Final = "Vendor Item ID"
ITEMS_ERP_ITEM_ID: Final = "ERP Item ID"
ITEMS_DESCRIPTION: Final = "Description"
ITEMS_TERMS_COMMITMENT: Final = "Commitment Term"
ITEMS_TERMS_MODEL: Final = "Billing Model"
ITEMS_TERMS_PERIOD: Final = "Billing Period"
ITEMS_STATUS: Final = "Status"
ITEMS_GROUP_ID: Final = "Group ID"
ITEMS_GROUP_NAME: Final = "Group Name"
ITEMS_UNIT_ID: Final = "Unit ID"
ITEMS_UNIT_NAME: Final = "Unit Name"
ITEMS_QUANTITY_APPLICABLE: Final = "Quantity Applicable"
ITEMS_CREATED: Final = CREATED_COLUMN_NAME
ITEMS_MODIFIED: Final = MODIFIED_COLUMN_NAME
ITEMS_REQUIRED_FIELDS: Final = (
    ITEMS_ID,
    ITEMS_NAME,
    ITEMS_ACTION,
    ITEMS_VENDOR_ITEM_ID,
    ITEMS_DESCRIPTION,
    ITEMS_TERMS_MODEL,
    ITEMS_TERMS_PERIOD,
    ITEMS_TERMS_COMMITMENT,
    ITEMS_GROUP_ID,
    ITEMS_UNIT_NAME,
    ITEMS_QUANTITY_APPLICABLE,
)
ITEMS_FIELDS: Final = (
    ITEMS_ID,
    ITEMS_NAME,
    ITEMS_ACTION,
    ITEMS_VENDOR_ITEM_ID,
    ITEMS_ERP_ITEM_ID,
    ITEMS_DESCRIPTION,
    ITEMS_TERMS_MODEL,
    ITEMS_TERMS_PERIOD,
    ITEMS_TERMS_COMMITMENT,
    ITEMS_STATUS,
    ITEMS_GROUP_ID,
    ITEMS_GROUP_NAME,
    ITEMS_UNIT_ID,
    ITEMS_UNIT_NAME,
    ITEMS_QUANTITY_APPLICABLE,
    ITEMS_CREATED,
    ITEMS_MODIFIED,
)

# Templates tab definition
TEMPLATES_ID: Final = ID_COLUMN_NAME
TEMPLATES_NAME: Final = "Name"
TEMPLATES_ACTION: Final = ACTION_COLUMN_NAME
TEMPLATES_TYPE: Final = "Type"
TEMPLATES_DEFAULT: Final = "Default"
TEMPLATES_CONTENT: Final = "Content"
TEMPLATES_CREATED: Final = CREATED_COLUMN_NAME
TEMPLATES_MODIFIED: Final = MODIFIED_COLUMN_NAME
TEMPLATES_REQUIRED_FIELDS: Final = (
    TEMPLATES_ID,
    TEMPLATES_NAME,
    TEMPLATES_ACTION,
    TEMPLATES_TYPE,
    TEMPLATES_CONTENT,
)
TEMPLATES_FIELDS: Final = (
    TEMPLATES_ID,
    TEMPLATES_NAME,
    TEMPLATES_ACTION,
    TEMPLATES_TYPE,
    TEMPLATES_DEFAULT,
    TEMPLATES_CONTENT,
    TEMPLATES_CREATED,
    TEMPLATES_MODIFIED,
)

# Settings tab definition
SETTINGS_SETTING: Final = "Setting"
SETTINGS_ACTION: Final = ACTION_COLUMN_NAME
SETTINGS_VALUE: Final = "Value"
SETTINGS_REQUIRED_FIELDS: Final = (
    SETTINGS_SETTING,
    SETTINGS_VALUE,
)
SETTINGS_API_MAPPING: Final = {
    "Change order validation (draft)": "preValidation.changeOrderDraft",
    "Item selection validation": "itemSelection",
    "Order queue changes notification": "orderQueueChanges",
    "Product ordering": "productOrdering",
    "Product requests": "productRequests.enabled",
    "Product requests. Request title": "productRequests.title",
    "Product requests. Call to action label": "productRequests.label",
    "Product request validation (draft)": "preValidation.productRequest",
    "Purchase order validation (draft)": "preValidation.purchaseOrderDraft",
    "Purchase order validation (query)": "preValidation.purchaseOrderQuery",
    "Termination order validation (draft)": "preValidation.terminationOrder",
}
SETTINGS_FIELDS: Final = (
    SETTINGS_SETTING,
    SETTINGS_ACTION,
    SETTINGS_VALUE,
)


REQUIRED_FIELDS_BY_TAB: Final = {
    TAB_GENERAL: GENERAL_REQUIRED_FIELDS,
    TAB_PARAMETERS_GROUPS: PARAMETERS_GROUPS_REQUIRED_FIELDS,
    TAB_ITEMS_GROUPS: ITEMS_GROUPS_REQUIRED_FIELDS,
    TAB_AGREEMENT_PARAMETERS: PARAMETERS_REQUIRED_FIELDS,
    TAB_ITEM_PARAMETERS: PARAMETERS_REQUIRED_FIELDS,
    TAB_REQUEST_PARAMETERS: PARAMETERS_REQUIRED_FIELDS,
    TAB_SUBSCRIPTION_PARAMETERS: PARAMETERS_REQUIRED_FIELDS,
    TAB_ITEMS: ITEMS_REQUIRED_FIELDS,
    TAB_TEMPLATES: TEMPLATES_REQUIRED_FIELDS,
    TAB_SETTINGS: SETTINGS_REQUIRED_FIELDS,
}

REQUIRED_FIELDS_WITH_VALUES_BY_TAB: Final = {
    TAB_GENERAL: GENERAL_REQUIRED_FIELDS_WITH_VALUES,
}
