TAB_GENERAL = "General"
TAB_PRICE_ITEMS = "Price Items"
REQUIRED_TABS = [
    TAB_GENERAL,
    TAB_PRICE_ITEMS,
]

GENERAL_PRICELIST_ID = "Pricelist ID"
GENERAL_CURRENCY = "Currency"
GENERAL_PRODUCT_ID = "Product ID"
GENERAL_PRODUCT_NAME = "Product Name"
GENERAL_VENDOR_ID = "Vendor ID"
GENERAL_VENDOR_NAME = "Vendor Name"
GENERAL_PRECISION = "Precision"
GENERAL_DEFAULT_MARKUP = "Default Markup"
GENERAL_NOTES = "Notes"
GENERAL_CREATED = "Created"
GENERAL_MODIFIED = "Modified"
GENERAL_FIELDS = [
    GENERAL_PRICELIST_ID,
    GENERAL_CURRENCY,
    GENERAL_PRODUCT_ID,
    GENERAL_PRODUCT_NAME,
    GENERAL_VENDOR_ID,
    GENERAL_VENDOR_NAME,
    GENERAL_PRECISION,
    GENERAL_DEFAULT_MARKUP,
    GENERAL_NOTES,
    GENERAL_CREATED,
    GENERAL_MODIFIED,
]

PRICELIST_ITEMS_ID = "ID"
PRICELIST_ITEMS_ITEM_ID = "Item ID"
PRICELIST_ITEMS_ITEM_NAME = "Item Name"
PRICELIST_ITEMS_ACTION = "Action"
PRICELIST_ITEMS_ITEM_VENDOR_ID = "Item Vendor ID"
PRICELIST_ITEMS_ITEM_ERP_ID = "Item ERP ID"
PRICELIST_ITEMS_BILLING_FREQUENCY = "Billing Frequency"
PRICELIST_ITEMS_COMMITMENT = "Commitment"
PRICELIST_ITEMS_UNIT_LP = "Unit LP"
PRICELIST_ITEMS_UNIT_PP = "Unit PP"
PRICELIST_ITEMS_MARKUP = "Markup"
PRICELIST_ITEMS_PPx1 = "PPx1"
PRICELIST_ITEMS_PPxM = "PPxM"
PRICELIST_ITEMS_PPxY = "PPxY"
PRICELIST_ITEMS_UNIT_SP = "Unit SP"
PRICELIST_ITEMS_SPx1 = "SPx1"
PRICELIST_ITEMS_SPxM = "SPxM"
PRICELIST_ITEMS_SPxY = "SPxY"
PRICELIST_ITEMS_LPx1 = "LPx1"
PRICELIST_ITEMS_LPxM = "LPxM"
PRICELIST_ITEMS_LPxY = "LPxY"
PRICELIST_ITEMS_STATUS = "Status"
PRICELIST_ITEMS_FIELDS = [
    PRICELIST_ITEMS_ID,
    PRICELIST_ITEMS_ITEM_ID,
    PRICELIST_ITEMS_ITEM_NAME,
    PRICELIST_ITEMS_ITEM_VENDOR_ID,
    PRICELIST_ITEMS_ITEM_ERP_ID,
    PRICELIST_ITEMS_BILLING_FREQUENCY,
    PRICELIST_ITEMS_COMMITMENT,
    PRICELIST_ITEMS_UNIT_LP,
    PRICELIST_ITEMS_UNIT_PP,
    PRICELIST_ITEMS_MARKUP,
    PRICELIST_ITEMS_PPx1,
    PRICELIST_ITEMS_PPxM,
    PRICELIST_ITEMS_PPxY,
    PRICELIST_ITEMS_UNIT_SP,
    PRICELIST_ITEMS_SPx1,
    PRICELIST_ITEMS_SPxM,
    PRICELIST_ITEMS_SPxY,
    PRICELIST_ITEMS_LPx1,
    PRICELIST_ITEMS_LPxM,
    PRICELIST_ITEMS_LPxY,
    PRICELIST_ITEMS_STATUS,
    PRICELIST_ITEMS_ACTION,
]
